### ISSUE TITLE
paragraph() vs paragraphs() output

### ISSUE THREAD

**Issue by AlexVanderbist** [spatie/seeders#11]
The `paragraph()` method outputs plain text whilst the `paragraphs()` method outputs some html paragraphs... 

Can we make `paragraph()` output a single html paragraph as well?

**Comment by sebastiandedeyne** [comment]
Hmm I occasionally use this to seed description-like fields that don't have any html markup.

I don't minding changing the behaviour here for consistency, but I'd still like to have an alternative for plain paragraphs :) (or does Faker already have this, forgot?)

**Comment by AlexVanderbist** [comment]
Just checked; looks like Faker's original `paragraph()`/`paragraphs()` methods return plain text or an array of plain text strings by default. Now it feels a bit weird to return html whilst the Faker docs say plain text...

Maybe we can add a `formattedParagraphs(int $num = 1)` method?

**Comment by sebastiandedeyne** [comment]
Maybe `htmlParagraphs`?
