### ISSUE TITLE
Faker localization

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/seeders#6]
Inspired by this thread that just got opened: https://github.com/laravel/internals/issues/398

What we want:

- By default, use `nl_BE`
- When using this packages' `translations` method, generate Faker stuff on the relevant locale

I have no idea how Faker is bound to the IoC in Laravel, so we'll need to research that first to overwrite the default locale.

**Comment by garygreen** [comment]
Quite easy really. It's registered [here](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/DatabaseServiceProvider.php#L77) all Laravel needs changing is:

```php
$this->app->singleton(FakerGenerator::class, function () {
  return FakerFactory::create();
});
```

to

```php
$this->app->singleton(FakerGenerator::class, function () {
  return FakerFactory::create(env('FAKER_LOCALE', 'en_US'));
});
```

Only thing is laravel doesn't actually make use of `env()` anywhere in its service providers, so maybe a config option would be better.
